
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Calendar calendario;
	
	private global::Gtk.Button btnAddEvento;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Agenda Master");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w1.X = 5;
		w1.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnAddEvento = new global::Gtk.Button ();
		this.btnAddEvento.CanFocus = true;
		this.btnAddEvento.Name = "btnAddEvento";
		this.btnAddEvento.UseUnderline = true;
		this.btnAddEvento.Label = global::Mono.Unix.Catalog.GetString ("Adicionar eventos");
		this.fixed1.Add (this.btnAddEvento);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnAddEvento]));
		w2.X = 262;
		w2.Y = 200;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.calendario.DaySelectedDoubleClick += new global::System.EventHandler (this.SelecionaDiaCalendario);
		this.btnAddEvento.Clicked += new global::System.EventHandler (this.btnAddEventoClicado);
	}
}
