
// This file has been generated by the GUI designer. Do not modify.
namespace Teste
{
	public partial class AdicionaEvento
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Teste.AdicionaEvento
			this.Name = "Teste.AdicionaEvento";
			this.Title = global::Mono.Unix.Catalog.GetString ("AdicionaEvento");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
